### ISSUE TITLE
Contributing map data

### ISSUE THREAD

**Issue by nuvasuper** [ccmap/ccmap.github.io#1]
Is this an appropriate place to contribute map data files?
https://pixeldra.in/u/_51YcF

**Comment by Gjum** [comment]
[Do this](https://github.com/gjum/civmap/wiki/Contributing#how-to-contribute-voxelmap-data) and then send me the archive on reddit/discord/mail.

I should put this in the readmes.

**Comment by nuvasuper** [comment]
What accounts do you use on those services?  I've arranged the file in pixeldrain according to those guidelines.

**Comment by Gjum** [comment]
Reddit: [u/Gjum](reddit.com/u/Gjum)

Discord: `@Gjum#5146`
